# This file extends docker-compose.yml
version: "3.4"

services:

  kamailio:
    command: ["tail","-f","/dev/null"]
    build:
      context: ../
      dockerfile: provisioning/Dockerfile
    ports:
      - 5060:5060/udp
    env_file: ../.env
    volumes:
      - ../etc:/usr/local/etc/kamailio
      - ../kamailio:/usr/src/kamailio
      - ../provisioning/docker-entrypoint.sh:/docker-entrypoint.sh
    networks:
      - signalwire_development

  registrar-redis:
    command: redis-server --appendonly no --maxmemory-policy allkeys-lru
    image: redis:4-alpine
    networks:
      - signalwire_development

  registrar:
    image: signalwire/registrar
    networks:
      - signalwire_development
    env_file: ../.env
    stdin_open: true
    tty: true

networks:
  signalwire_development:
    external: true
