# This file extends docker-compose.yml
version: "3.4"

services:

  kamailio:
    build:
      context: ../
      dockerfile: provisioning/Dockerfile
    ports:
      - 5060:5060/udp
    env_file: ../.env
    networks:
      - signalwire_freeswitch

networks:
  signalwire_freeswitch:
    external: true
