name: build and test kamailio

on:
  push:
    branches:
    - master
    - sa/3962-remove-blade

  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GH_BOT_DEPLOY_KEY:
        required: true

jobs:

  production-pre:
    name: 'production-pre'
    uses: signalwire/actions-template/.github/workflows/ci-build.yml@main
    with:
      PROJECT_NAME: 'kamailio'
      FILE: ./provisioning/production.Dockerfile
      PUSH: 'true'
      ENABLE_GPG: true
      TAG: |
        type=raw,value=production-pre
      SUBMODULES_RECURSIVE: true
      SUBMODULES_PRIVATE: false
    secrets:
      GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GH_BOT_DEPLOY_KEY: ${{ secrets.GH_BOT_DEPLOY_KEY }}

  production-pre-test:
    needs: production-pre
    runs-on: ubuntu-latest
    container:
      image: signalwire/kamailio:production-pre
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    services:
      registrar-redis:
        image: redis:4-alpine
      switchblade:
        image: signalwire/switchblade:staging
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          SWITCHBLADE_MODE: Master
          SWITCHBLADE_HOST: switchblade
          SWITCHBLADE_DAEMON: 'true'
          ELASTIC_APM_ENABLED: 'false'
      registrar:
        image: signalwire/registrar:unstable
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          REGISTRAR_REDIS: registrar-redis:6379
          REGISTRAR_WEB_HOST_PORT: 8080
          REGISTRAR_DAEMON: true

    env:
      REGISTRAR_URI: http://registrar:8080/sip/
    steps:
    - name: Tools
      run: apt update && apt install -yq procps curl netcat-openbsd net-tools redis-tools

    - name: Start Kamailio
      # docker-entrypoint.sh is really cute but relies on confd
      run: /usr/local/sbin/kamailio -DD -dd -E -m 2048 -M 24 -A 'KAM_CLUSTER_NONCE="boo!"' -A 'KAM_IP_LOCAL=0.0.0.0' -A 'KAM_IP_PUBLIC=0.0.0.0' -A 'KAMAILIO_SIPTRACE_SOURCE_IP=0.0.0.0' -A 'KAMAILIO_DEVELOPMENT=true' --log-engine=json:acA &

    - name: Netstat
      run: netstat -tunap

    - name: Ensure Kamailio is running
      run: curl -v http://127.0.0.1:5060/

    - name: Add entry to registrar
      run: 'echo -e
          "REGISTER bob@example.com SIP/2.0/tcp\r\n"
          "Via SIP/2.0/tcp 127.0.0.1:5080;branch=one\r\n"
          "From: bob@example.com;tag=foo\r\n"
          "To: bob@example.com\r\n"
          "Call-ID: 123\r\n"
          "CSeq: 1 REGISTER\r\n"
          "Contact: sip:bob@127.0.0.1:5080\r\n"
          "Content-Length: 0\r\n"
          "Expires: 300\r\n"
          "\r\n"
          | nc -v -p 5080 localhost 5060'

    - name: Stop Kamailio
      run: pkill kamailio
