name: build and test kamailio

on:
  push:
    branches:
    - master
    - sa/3962-remove-blade

  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GH_BOT_DEPLOY_KEY:
        required: true

jobs:

  production-pre:
    runs-on:
    - ubuntu-latest

    outputs:
      imagetag: ${{ steps.meta.outputs.tags }}

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          signalwire/kamailio
        tags: |
          type=raw,value=production-pre

    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.GH_BOT_DEPLOY_KEY }}
        submodules: 'recursive'

    - name: Build and export to Docker
      uses: docker/build-push-action@v3
      with:
        # `context` is required to re-use the outcome of `actions/checkout`
        context: .
        push: true
        file: provisioning/production.Dockerfile
        ssh: ${{ env.SSH_AUTH_SOCK }}
        tags: ${{ steps.meta.outputs.tags }}

  production-pre-test:
    needs: production-pre
    runs-on: ubuntu-latest
    container:
      image: signalwire/kamailio:production-pre
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    services:
      registrar-redis:
        image: redis:4-alpine
      switchblade:
        image: signalwire/switchblade:staging
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          SWITCHBLADE_MODE: Master
          SWITCHBLADE_HOST: switchblade
          SWITCHBLADE_DAEMON: 'true'
          ELASTIC_APM_ENABLED: 'false'
      registrar:
        image: signalwire/registrar:production-pre
        env:
          REGISTRAR_REDIS: registrar-redis:6379
          REGISTRAR_WEB_HOST_PORT: 8080
          REGISTRAR_DAEMON: true

    env:
      REGISTRAR_URI: http://registrar:8080/sip/
    steps:
    - name: Tools
      run: apt update && apt install -yq procps

    - name: Start Kamailio
      run: /docker-entrypoint.sh

    - name: Stop Kamailio
      run: pkill kamailio
