name: build and test kamailio

on:
  push:
    branches:
    - master
    - sa/3962-remove-blade

  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GH_BOT_DEPLOY_KEY:
        required: true

jobs:

  build:
    name: 'Staging GCP'
    uses: signalwire/actions-template/.github/workflows/ci-build.yml@dev
    with:
      PROJECT_NAME: "kamailio"
      FILE: ./provisioning/production.Dockerfile
      ENABLE_GPG: true
      SUBMODULES_RECURSIVE: true
    secrets:
      GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GH_BOT_DEPLOY_KEY: ${{ secrets.GH_BOT_DEPLOY_KEY }}

  production-pre:
    name: 'production-pre'
    uses: signalwire/actions-template/.github/workflows/ci-build.yml@main
    with:
      PROJECT_NAME: 'kamailio'
      FILE: provisioning/production.Dockerfile
      PUSH: true
      TAG: |
        type=raw,value=production-pre
      SUBMODULES_RECURSIVE: true
    secrets:
      GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GH_BOT_DEPLOY_KEY: ${{ secrets.GH_BOT_DEPLOY_KEY }}

  production-pre-test:
    needs: production-pre
    runs-on: ubuntu-latest
    container:
      image: signalwire/kamailio:production-pre
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    services:
      registrar-redis:
        image: redis:4-alpine
      switchblade:
        image: signalwire/switchblade:staging
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          SWITCHBLADE_MODE: Master
          SWITCHBLADE_HOST: switchblade
          SWITCHBLADE_DAEMON: 'true'
          ELASTIC_APM_ENABLED: 'false'
      registrar:
        image: signalwire/registrar:production-pre
        env:
          REGISTRAR_REDIS: registrar-redis:6379
          REGISTRAR_WEB_HOST_PORT: 8080
          REGISTRAR_DAEMON: true

    env:
      REGISTRAR_URI: http://registrar:8080/sip/
    steps:
    - name: Tools
      run: apt update && apt install -yq procps

    - name: Start Kamailio
      run: /docker-entrypoint.sh

    - name: Stop Kamailio
      run: pkill kamailio
